"""empty message

Revision ID: 132a8b8edac8
Revises: 
Create Date: 2021-08-12 21:48:27.209772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '132a8b8edac8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daysofweek',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eng_short_name', sa.String(), nullable=False),
    sa.Column('eng_full_name', sa.String(), nullable=False),
    sa.Column('rus_full_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('eng_full_name'),
    sa.UniqueConstraint('eng_short_name'),
    sa.UniqueConstraint('rus_full_name')
    )
    op.create_table('goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('emoji', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('timeforpractice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description')
    )
    op.create_table('tutors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('about', sa.String(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('picture', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('free', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_name', sa.String(), nullable=False),
    sa.Column('client_phone', sa.String(), nullable=False),
    sa.Column('time', sa.String(), nullable=False),
    sa.Column('class_day', sa.String(), nullable=False),
    sa.Column('tutor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tutor_id'], ['tutors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_name', sa.String(), nullable=False),
    sa.Column('client_phone', sa.String(), nullable=False),
    sa.Column('time_for_practice_id', sa.Integer(), nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ),
    sa.ForeignKeyConstraint(['time_for_practice_id'], ['timeforpractice.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tutor_goals',
    sa.Column('tutor_id', sa.Integer(), nullable=True),
    sa.Column('goal_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ),
    sa.ForeignKeyConstraint(['tutor_id'], ['tutors.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tutor_goals')
    op.drop_table('requests')
    op.drop_table('bookings')
    op.drop_table('tutors')
    op.drop_table('timeforpractice')
    op.drop_table('goals')
    op.drop_table('daysofweek')
    # ### end Alembic commands ###
